CREATE DATABASE testDB1;
CREATE DATABASE testDB2;
SHOW DATABASES;

USE testDB1;

CREATE TABLE CUSTOMERS(
  ID   INT              NOT NULL,
  NAME VARCHAR (20)     NOT NULL,
  AGE  INT              NOT NULL,
  ADDRESS  CHAR (25) ,
  SALARY   DECIMAL (18, 2),  /* The (18,2) simply means that we can have 18 digits with 2 of them after decimal point*/
  PRIMARY KEY (ID)
);

INSERT INTO CUSTOMERS (ID, NAME, AGE, ADDRESS, SALARY)
VALUES (1, 'Mark', 32, 'Texas', 50000.00 );

INSERT INTO CUSTOMERS (ID, NAME, AGE, ADDRESS, SALARY)
VALUES (2, 'John', 25, 'NY', 65000.00 );

INSERT INTO CUSTOMERS (ID, NAME, AGE, ADDRESS, SALARY)
VALUES (3, 'Emily', 23, 'Ohio', 20000.00 );

INSERT INTO CUSTOMERS (ID, NAME, AGE, ADDRESS, SALARY)
VALUES (4, 'Bill', 25, 'Chicago', 75000.00 );

INSERT INTO CUSTOMERS (ID, NAME, AGE, ADDRESS, SALARY)
VALUES (5, 'Tom', 27, 'Washington', 35000.00 );

INSERT INTO CUSTOMERS (ID, NAME, AGE, ADDRESS, SALARY)
VALUES (6, 'Jane', 22, 'Texas', 45000.00 );

SELECT ID, NAME, SALARY FROM CUSTOMERS;

-- or 

SELECT * FROM CUSTOMERS;

-- WHERE
SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 50000;

SELECT * FROM CUSTOMERS WHERE NAME = 'John';

-- AND CLAUSE
-- SELECT column1, column2 FROM table_name WHERE [condition1] AND [condition2]
SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY >= 20000 AND age < 25;

-- OR CLAUSE
-- SELECT column1, column2, ... columnN FROM table_name WHERE [condition1] OR [condition2]...OR [conditionN];
SELECT ID, NAME, SALARY FROM CUSTOMERS WHERE SALARY > 50000 OR age < 25;